### PR TITLE
Refactor with ByteTransformer and InputStreamFactory

### PR DESCRIPTION
**Pull request by alexmojaki**
This deduplicates much of the boilerplate around handling streams, files, and command-line arguments in the Java code. It adds an abstract base class `ByteTransformer` which the 6 compressors/decompressors all extend.

`ByteTransformer` works on abstract streams (maybe I should rename it to `StreamTransformer` :thinking:)  so that it can be used easily with files for the CLI and with byte arrays for the tests. In particular the non-adaptive arithmetic compression/decompression logic has been naturally deduplicated between the tests and CLI, especially the handling of the static frequency table. This means that the CLI is better covered by the same test suite and almost no remaining code is left untested, although testing the CLI code would also now be much easier.

I really appreciate that this repo exists as I'm teaching myself data compression. I hope you'll agree that these changes make the code even more readable, as the added abstractions are very simple and they remove unimportant distractions that make the differences between the algorithms clearer. Let me know if there are any changes you'd like me to make to the PR to suit your preferences,

### CODE REVIEW

**Comment by alexmojaki** [comment]
Further refactoring on top of this PR is in https://github.com/alexmojaki/Reference-arithmetic-coding/pull/1. I didn't include it here because it might be pushing things a bit. Here's a link to a full comparison between that branch and this repo: https://github.com/nayuki/Reference-arithmetic-coding/compare/master...alexmojaki:compressor

**Comment by nayuki** [comment]
Thanks for the effort. Sorry, I don't like this architecture.

**Comment by alexmojaki** [comment]
Can you elaborate? Do you think it makes the code harder to understand? Is there something you think is unclear or overcomplicated?

**Comment by nayuki** [comment]
I don't know how well I conveyed my intentions, but this project is an implementation of arithmetic coding core algorithms and a couple of _sample_ programs for educational purposes. It is not a popular, established file format. It is not a reusable framework that would warrant things like `ByteTransformer`. None of the `main()` programs are considered precious.

An incomplete list of deficiencies I see:

* While the idea of testing CLI programs has merits, there are a lot of downsides as well. CLIs only take string arguments, not objects or streams. Some effort would be needed to create appropriate mock objects. Given these limitations, I feel that the better choice is to make the CLI program dead-simple and rely on simply reading the source code to ensure that it does what it's supposed to do. I believe that trying to fit CLI programs into a test framework would add complication with little benefit - especially given that these programs are just educational samples, not critical infrastructure that others rely on.

* I'm not sure what benefit an `InputStreamFactory` has over an `InputStream`.

* `ByteTransformer` instances appear to be stateless. It would be better to have singletons instead of creating instances.

* Changing from specific imports to wildcard imports is discouraged in pretty much all languages. For Java, e.g. https://stackoverflow.com/questions/147454/why-is-using-a-wild-card-with-a-java-import-statement-bad . In C++, `using namespace std;` is almost universally considered bad.

**Comment by alexmojaki** [comment]
> I don't know how well I conveyed my intentions, but this project is an implementation of arithmetic coding core algorithms and a couple of _sample_ programs for educational purposes. It is not a popular, established file format. It is not a reusable framework that would warrant things like `ByteTransformer`. None of the `main()` programs are considered precious.
> 
> An incomplete list of deficiencies I see:
> 
> * While the idea of testing CLI programs has merits, there are a lot of downsides as well. CLIs only take string arguments, not objects or streams. Some effort would be needed to create appropriate mock objects. Given these limitations, I feel that the better choice is to make the CLI program dead-simple and rely on simply reading the source code to ensure that it does what it's supposed to do. I believe that trying to fit CLI programs into a test framework would add complication with little benefit - especially given that these programs are just educational samples, not critical infrastructure that others rely on.

Here's my personal experience: I want to use the code here as a starting point to experiment with my own compression ideas. Tweak things here and there to see if I can improve the speed or compression ratio. As a novice, I'd much rather do that with a simple, clear codebase than a complex, highly optimised library, which is why I'm here.

When I make changes, I want to be able to test them. First I want to test that I haven't broken anything, and the unit tests are good for that. Secondly I want to test if there's actually been an improvement. The unit tests are not so good for that since they work on small byte arrays, with good reason. I want to see what the difference is when I run my modified algorithm on e.g. a 10mb file. So I want to run the CLI programs.

Here's the duplicated code:

```java
		FrequencyTable freqs = new SimpleFrequencyTable(new int[257]);
		for (byte x : b)
			freqs.increment(x & 0xFF);
		freqs.increment(256);  // EOF symbol gets a frequency of 1
		
		InputStream in = new ByteArrayInputStream(b);
		ByteArrayOutputStream out = new ByteArrayOutputStream();
		try (BitOutputStream bitOut = new BitOutputStream(out)) {
			ArithmeticCompress.writeFrequencies(bitOut, freqs);
			ArithmeticCompress.compress(freqs, in, bitOut);
		}
		return out.toByteArray();
```

```java
		// Read input file once to compute symbol frequencies
		FrequencyTable freqs = getFrequencies(inputFile);
		freqs.increment(256);  // EOF symbol gets a frequency of 1
		
		// Read input file again, compress with arithmetic coding, and write output file
		try (InputStream in = new BufferedInputStream(new FileInputStream(inputFile));
				BitOutputStream out = new BitOutputStream(new BufferedOutputStream(new FileOutputStream(outputFile)))) {
			writeFrequencies(out, freqs);
			compress(freqs, in, out);
		}
	}
	
	
	// Returns a frequency table based on the bytes in the given file.
	// Also contains an extra entry for symbol 256, whose frequency is set to 0.
	private static FrequencyTable getFrequencies(File file) throws IOException {
		FrequencyTable freqs = new SimpleFrequencyTable(new int[257]);
		try (InputStream input = new BufferedInputStream(new FileInputStream(file))) {
			while (true) {
				int b = input.read();
				if (b == -1)
					break;
				freqs.increment(b);
			}
		}
		return freqs;
	}
```

I want to experiment with changes that are not contained entirely within the deduplicated 'API' like `compress` and `writeFrequencies`. For example, I want to collect frequencies of n-grams in advance. That means rewriting `getFrequencies` as well as the corresponding code in the tests.

It doesn't have to be that way. This is a simple refactoring that keeps all the actual compression logic in one place, so that's the only place I have to make changes to experiment with algorithms. Now the only difference between the tests and the CLI is these two methods that have nothing to do with compression algorithms:

```java
	public void transformFile(String inputFile, String outputFile) throws IOException {
		InputStreamFactory factory = new FileInputStreamFactory(inputFile);
		OutputStream out = new BufferedOutputStream(new FileOutputStream(outputFile));
		transformStream(factory, out);
	}

	public byte[] transformByteArray(byte[] b) throws IOException {
		InputStreamFactory factory = new ByteInputStreamFactory(b);
		ByteArrayOutputStream out = new ByteArrayOutputStream();
		transformStream(factory, out);
		return out.toByteArray();
	}
```

Now the difference between tested and untested code is much smaller, and I'm much less likely to need to make changes to the untested part, so it doesn't matter. I'm not suggesting creating mock objects or anything like that, I don't know where that idea came from.

> * I'm not sure what benefit an `InputStreamFactory` has over an `InputStream`.

Non-adaptive arithmetic coding has to read the same data twice so that it can get the frequencies first. An alternative would be to use `mark` and `reset`, but it looked like that wouldn't work well for files.

In https://github.com/alexmojaki/Reference-arithmetic-coding/pull/1 you can see that most implementations only need the stream once, so they can just override `compress` or `decompress` and work with a stream directly instead of a factory. `ArithmeticCompress` stands out more clearly as the exception that needs the factory so it can call `getStream` again directly.

I can add comments to the classes to make this clearer.

> * `ByteTransformer` instances appear to be stateless. It would be better to have singletons instead of creating instances.

I can add a static `getInstance()` or `SINGLETON` to each class if you want, although I don't personally think it'd achieve much. I wish Java had an equivalent to Python's `@classmethod` so that this could be defined once in the base class. Similarly it's annoying to still have to add `public static void main` to each class.

> * Changing from specific imports to wildcard imports is discouraged in pretty much all languages. For Java, e.g. https://stackoverflow.com/questions/147454/why-is-using-a-wild-card-with-a-java-import-statement-bad . In C++, `using namespace std;` is almost universally considered bad.

That's just something my IDE does automatically when I press the shortcut to remove unused imports. I've configured it to not do that.

**Comment by nayuki** [comment]
I gave a second reading to your code changes and comment thread. I decided to close this as it does not fit with my vision for the project.

**Pull request closed without merging**
